baseURL = "https://deiveleal.de"
languageCode = "en-us"
title = "Deive Leal"
theme = "hugo-profile"
paginate = 3
enableRobotsTXT = true
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "G-MEASUREMENT_ID"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog posts"
  url = "/blogs"
  weight = 1

[[menu.main]]
  identifier = "gallery"
  name = "Gallery"
  title = "Blog posts"
  url = "/gallery"
  weight = 2

# [[menu.main]]
#   identifier = "dropdown"
#   title = "Example dropdown menu"
#   name = "Dropdown"
#   weight = 3

# [[menu.main]]
#   identifier = "dropdown1"
#   title = "example dropdown 1"
#   name = "example 1"
#   url = "/#"
#   parent = "dropdown"
#   weight = 1

# [[menu.main]]
#   identifier = "dropdown2"
#   title = "example dropdown 2"
#   name = "example 2"
#   url = "/#"
#   parent = "dropdown"
#   weight = 2

[params]
  title = "Hugo Profile"
  description = "Text about my cool site"
  # staticPath = ""  # The path to serve the static files from
  favicon = "/fav.png"
  useBootstrapCDN = false